# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculum',
            name='root_path',
            field=models.CharField(max_length=1024),
        ),
    ]
