# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculum', '0003_auto_20160803_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputpath',
            old_name='input_path',
            new_name='input_paths',
        ),
    ]
