# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculum', '0004_auto_20160803_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputpath',
            old_name='input_paths',
            new_name='input_path',
        ),
    ]
