# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculum', '0006_auto_20160804_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteresources',
            name='output_path',
        ),
    ]
