# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculum', '0007_remove_remoteresources_output_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutputpath',
            name='output_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
